import { createClient } from "@sanity/client";

const client = createClient({
  projectId: "730sqy7i",
  dataset: "production",
  apiVersion: "2024-01-01",
  token: "skDV9tZVduVpVwHtOymHvjqA0gIOTCCoFec7GuiONFWHGbk7wUKY57OdSrbFXMqoJjLaGf8efHT8CXYsd",
  useCdn: false,
});

// Category name → Sanity _id mapping
const CATEGORY_MAP = {
  "Youth": "eventCategory-youth",
  "Branch Anniversary": "eventCategory-branch-anniversary",
  "Prayer Night": "eventCategory-prayer-night",
  "Special Service": "eventCategory-special-service",
  "Marriage & Family": "eventCategory-marriage-and-family",
  "Guest Speaker": "eventCategory-guest-speaker",
  "Interbranch Overnight": "eventCategory-interbranch-overnight",
  "Women's Ministry": "eventCategory-womens-ministry",
  "Women's Conference": "eventCategory-womens-conference",
  "Conference": "eventCategory-conference",
  "Family": "eventCategory-family",
  "Anniversary": "eventCategory-anniversary",
  "Leadership": "eventCategory-leadership",
  "Celebration": "eventCategory-celebration",
  "Men's Conference": "eventCategory-mens-conference",
};

// Parse display dates like "11th January 2026", "8th–10th May 2026", "23rd–26th February 2026"
function parseStartDate(displayDate) {
  // Handle "April 2026" (no day)
  const monthOnlyMatch = displayDate.match(/^([A-Z][a-z]+)\s+(\d{4})$/);
  if (monthOnlyMatch) {
    const d = new Date(`1 ${monthOnlyMatch[1]} ${monthOnlyMatch[2]}`);
    if (!isNaN(d)) return d.toISOString().slice(0, 10);
  }

  // Extract first date from ranges like "8th–10th May 2026"
  const cleaned = displayDate
    .replace(/–.*?(?=\s+[A-Z])/, "") // remove "–10th" before month
    .replace(/–\d+\w*\s+/, " ")      // remove "–26th " in middle
    .replace(/(st|nd|rd|th)/g, "");   // remove ordinal suffixes

  const d = new Date(cleaned);
  if (!isNaN(d)) return d.toISOString().slice(0, 10);

  // Fallback: try extracting just the first number + month + year
  const m = displayDate.match(/(\d+)\w*\s+([A-Z][a-z]+)\s+(\d{4})/);
  if (m) {
    const d2 = new Date(`${m[1]} ${m[2]} ${m[3]}`);
    if (!isNaN(d2)) return d2.toISOString().slice(0, 10);
  }

  console.warn(`  Could not parse date: "${displayDate}"`);
  return null;
}

// All 65 events from local data
const LOCAL_EVENTS = [
  { id: "teens-ministry-anniversary", name: "Teens Ministry Anniversary", date: "11th January 2026", time: "9:00 AM – 4:00 PM", location: "Christ's Heart Kampala", description: "A vibrant celebration honouring the Teens Ministry of Christ's Heart Ministries International. Young people from all branches come together for an electrifying day of worship, dance, spoken word, and testimonies. Featuring guest youth speakers, mentorship sessions, and powerful ministry time dedicated to raising a generation bold in faith and purpose.", tagline: "Raising a Generation Bold in Faith.", category: "Youth", isMajor: false },
  { id: "anniversary-chmi-uk", name: "Anniversary CHMI UK", date: "18th January 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart UK", description: "Celebrating the faithfulness of God over the UK branch of Christ's Heart Ministries International. A special anniversary service featuring worship, testimonies, and a powerful word from the leadership. Members and friends gather to mark another year of God's grace in the diaspora.", tagline: "God's Grace Across the Nations.", category: "Branch Anniversary", isMajor: false },
  { id: "mukono-overnight-jan", name: "Mukono Overnight", date: "31st January 2026", time: "8:00 PM – 6:00 AM", location: "Christ's Heart Mukono", description: "An all-night prayer and worship experience at our Mukono branch. Believers gather for extended intercession, prophetic declarations, and a deep encounter with the Holy Spirit. The Mukono Overnight is a monthly anchor event where we press into God's presence and receive fresh direction for the season ahead.", tagline: "A Night in His Presence Changes Everything.", category: "Prayer Night", isMajor: true },
  { id: "anniversary-chmi-lugazi-kira", name: "Anniversary CHMI Lugazi & Kira", date: "8th February 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Lugazi & Kira", description: "A joint celebration of the Lugazi and Kira branches as they mark another year of God's faithfulness. Special services at both locations with worship, testimonies, and preaching. A day to celebrate what God has done and decree what He is about to do in these communities.", tagline: "Two Branches, One God, One Celebration.", category: "Branch Anniversary", isMajor: false },
  { id: "breaking-the-fast", name: "Breaking the Fast", date: "10th February 2026", time: "12:00 PM – 3:00 PM", location: "Christ's Heart Kampala", description: "A powerful fellowship gathering as the church comes together to break a season of corporate fasting. Featuring thanksgiving worship, communion, shared meals, and a celebratory atmosphere as we mark the end of our consecration season. Expect testimonies of answered prayers and breakthroughs from the fast.", tagline: "The Fast Is Over. The Breakthrough Is Here.", category: "Special Service", isMajor: false },
  { id: "anniversary-chmi-mayuge", name: "Anniversary CHMI Mayuge", date: "15th February 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Mayuge", description: "Celebrating the Mayuge branch of Christ's Heart Ministries as they commemorate another year of growth, miracles, and kingdom advancement. A day of worship, thanksgiving, and prophetic declarations over the Mayuge community.", tagline: "Mayuge Celebrates God's Faithfulness.", category: "Branch Anniversary", isMajor: false },
  { id: "marriage-flair", name: "Marriage Flair", date: "21st February 2026", time: "9:00 AM – 5:00 PM", location: "Christ's Heart Kampala", description: "A powerful celebration of love, covenant, and God's design for marriage. Marriage Flair brings couples and singles together for a day of teaching, testimonies, and prayer focused on building strong, God-honouring homes. Featuring practical sessions on communication, intimacy, and raising godly families.", tagline: "Celebrate Love. Build God's Way.", category: "Marriage & Family", isMajor: true },
  { id: "bishop-victory-godspower-kla", name: "Bishop Victory Godspower – KLA", date: "22nd February 2026", time: "9:00 AM – 1:00 PM", location: "Christ's Heart Kampala", description: "A special Sunday service featuring the internationally renowned Bishop Victory Godspower. Experience a powerful ministration of the Word, prophetic declarations, and an atmosphere of signs and wonders. An unmissable opportunity to receive a fresh impartation from this anointed vessel of God.", tagline: "A Word From Heaven. A Shift in Your Season.", category: "Guest Speaker", isMajor: true },
  { id: "anniversary-chmi-mityana-kagoma", name: "Anniversary CHMI Mityana & Kagoma", date: "22nd February 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Mityana & Kagoma", description: "A joyous joint anniversary celebration for the Mityana and Kagoma branches. Believers from both communities gather to give God praise for His sustaining grace and to look ahead with faith. Featuring worship, shared testimonies, and an anointed word from leadership.", tagline: "Together in Faith, Together in Celebration.", category: "Branch Anniversary", isMajor: true },
  { id: "lunch-hour-bishop-victory", name: "Lunch Hour with Bishop Victory Godspower", date: "23rd February 2026", time: "12:00 PM – 2:00 PM Daily", location: "Christ's Heart Kampala", description: "Four days of powerful midday encounters with Bishop Victory Godspower. These lunch-hour sessions are designed for the working class and students — short, intense, and loaded with the fire of God. Come during your lunch break and leave with a fresh word, fresh fire, and fresh direction for your life.", tagline: "Your Lunch Hour Will Never Be the Same.", category: "Guest Speaker", isMajor: true },
  { id: "promise-fellowship-bishop-victory", name: "Promise Fellowship with Bishop Victory Godspower", date: "25th February 2026", time: "5:00 PM – 8:00 PM", location: "Christ's Heart Kampala", description: "A special evening fellowship with Bishop Victory Godspower focusing on the promises of God. An evening of deep teaching, prophetic ministry, and covenant declarations. Come and lay hold of what God has spoken over your life, family, and ministry.", tagline: "Hold On to Every Promise. God Is Faithful.", category: "Guest Speaker", isMajor: true },
  { id: "mukono-overnight-feb", name: "Mukono Overnight", date: "28th February 2026", time: "8:00 PM – 6:00 AM", location: "Christ's Heart Mukono", description: "An all-night prayer and worship experience at our Mukono branch. Believers gather for extended intercession, prophetic declarations, and a deep encounter with the Holy Spirit. The Mukono Overnight is a monthly anchor event where we press into God's presence and receive fresh direction for the season ahead.", tagline: "A Night in His Presence Changes Everything.", category: "Prayer Night", isMajor: true },
  { id: "anniversary-chmi-soroti", name: "Anniversary CHMI Soroti", date: "3rd March 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Soroti", description: "Celebrating the Soroti branch as it marks another year of gospel impact in the Teso region. A day filled with worship, powerful testimonies, and a celebratory message from leadership. The Soroti community comes together to honour God for His faithfulness.", tagline: "Soroti Rises in Praise.", category: "Branch Anniversary", isMajor: false },
  { id: "interbranch-overnight-kyebando-mar", name: "Interbranch Overnight Kyebando", date: "13th March 2026", time: "8:00 PM – 6:00 AM", location: "Christ's Heart Kyebando", description: "An electrifying all-night gathering at the Kyebando branch where multiple branches converge for a unified night of prayer, worship, and fellowship. The interbranch format creates a powerful atmosphere as believers from different communities join their faith together in one accord.", tagline: "Many Branches. One Fire.", category: "Interbranch Overnight", isMajor: false },
  { id: "mass-wedding", name: "Mass Wedding", date: "14th March 2026", time: "10:00 AM – 4:00 PM", location: "Christ's Heart Kampala", description: "A glorious ceremony where multiple couples exchange vows and begin their married life before God, family, and the church. The Mass Wedding is one of CHMI's most beautiful events — celebrating love, covenant, and community. Featuring a full wedding service, reception, and blessings from the senior leadership.", tagline: "Covenant Love. Kingdom Beginnings.", category: "Marriage & Family", isMajor: true },
  { id: "anniversary-chmi-entebbe", name: "Anniversary CHMI Entebbe", date: "15th March 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Entebbe", description: "The Entebbe branch celebrates another year of God's goodness. A special anniversary service with worship, testimonies of transformation, and a powerful word to set the tone for the year ahead. The lakeside community gathers to glorify God for every victory.", tagline: "Entebbe Celebrates God's Goodness.", category: "Branch Anniversary", isMajor: false },
  { id: "anniversary-chmi-mubende", name: "Anniversary CHMI Mubende", date: "22nd March 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Mubende", description: "Celebrating the Mubende branch's growth and impact in the community. A day of worship, thanksgiving, and prophetic declarations as the church honours God's faithfulness and looks ahead with expectation.", tagline: "Mubende Stands in Faith.", category: "Branch Anniversary", isMajor: false },
  { id: "anniversary-chmi-hoima", name: "Anniversary CHMI Hoima", date: "26th March 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Hoima", description: "The Hoima branch marks another year of God's grace with a powerful anniversary service. Believers gather to celebrate testimonies of healing, provision, and spiritual growth. A day of gratitude and fresh vision for the Hoima community.", tagline: "Hoima Honours God's Grace.", category: "Branch Anniversary", isMajor: false },
  { id: "virtuous-woman-run", name: "Virtuous Woman Run", date: "28th March 2026", time: "6:00 AM – 12:00 PM", location: "Kampala City", description: "An exciting charity run and fitness event organised by the women of Christ's Heart Ministries. The Virtuous Woman Run combines physical wellness with spiritual empowerment — a fun, energetic morning of running, walking, and fellowship followed by a short devotional and prayer. Open to women of all ages and fitness levels.", tagline: "Run With Purpose. Walk in Strength.", category: "Women's Ministry", isMajor: true },
  { id: "anniversary-chmi-mbale", name: "Anniversary CHMI Mbale", date: "29th March 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Mbale", description: "The Mbale branch celebrates God's faithfulness with a special anniversary service. Worship, testimonies, and a powerful word mark this joyous occasion as the eastern Uganda community gives God all the glory.", tagline: "Mbale Declares God's Faithfulness.", category: "Branch Anniversary", isMajor: false },
  { id: "mukono-overnight-mar", name: "Mukono Overnight", date: "28th March 2026", time: "8:00 PM – 6:00 AM", location: "Christ's Heart Mukono", description: "An all-night prayer and worship experience at our Mukono branch. Believers gather for extended intercession, prophetic declarations, and a deep encounter with the Holy Spirit. Press into God's presence and receive fresh direction for the season ahead.", tagline: "A Night in His Presence Changes Everything.", category: "Prayer Night", isMajor: true },
  { id: "anniversary-chmi-butaleja", name: "Anniversary CHMI Butaleja", date: "2nd April 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Butaleja", description: "Celebrating the Butaleja branch as it marks another year of gospel impact. A special anniversary service filled with worship, heartfelt testimonies, and a word from leadership. The Butaleja community gathers to honour God's sustaining grace.", tagline: "Butaleja Celebrates Another Year.", category: "Branch Anniversary", isMajor: false },
  { id: "easter-celebration", name: "Easter Celebration", date: "5th April 2026", time: "9:00 AM – 1:00 PM", location: "Christ's Heart Kampala – All Branches", description: "Join us for a glorious Easter Sunday celebration as we commemorate the resurrection of our Lord Jesus Christ. A powerful service of worship, thanksgiving, and declaration that He is risen. Believers from all branches come together to celebrate the victory of the cross and the power of the empty tomb.", tagline: "He Is Risen. Victory Is Ours.", category: "Special Service", isMajor: true },
  { id: "interbranch-overnight-nansana-apr", name: "Interbranch Overnight Nansana", date: "10th April 2026", time: "8:00 PM – 6:00 AM", location: "Christ's Heart Nansana", description: "A powerful all-night gathering at the Nansana branch where multiple branches come together for a unified night of prayer, worship, and deep fellowship. Experience the power of corporate intercession as believers from different communities join in one accord.", tagline: "United in Prayer Through the Night.", category: "Interbranch Overnight", isMajor: false },
  { id: "anniversary-chmi-kabale", name: "Anniversary CHMI Kabale", date: "26th April 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Kabale", description: "The Kabale branch celebrates another milestone year with a special anniversary service. Nestled in the hills of south-western Uganda, this community gathers to worship, testify, and receive a fresh word from God for the season ahead.", tagline: "Kabale Rises in Worship.", category: "Branch Anniversary", isMajor: false },
  { id: "pastor-olashore", name: "Pastor Olashore – Special Ministration", date: "April 2026", time: "To Be Confirmed", location: "Christ's Heart Kampala", description: "A highly anticipated visit from Pastor Olashore for a special ministration at Christ's Heart Kampala. Dates to be confirmed — stay tuned for details on what promises to be a powerful encounter with the Word and the Spirit.", tagline: "A Divine Appointment Awaits.", category: "Guest Speaker", isMajor: true },
  { id: "mukono-overnight-apr", name: "Mukono Overnight", date: "25th April 2026", time: "8:00 PM – 6:00 AM", location: "Christ's Heart Mukono", description: "An all-night prayer and worship experience at our Mukono branch. Believers gather for extended intercession, prophetic declarations, and a deep encounter with the Holy Spirit. Press into God's presence and receive fresh direction.", tagline: "A Night in His Presence Changes Everything.", category: "Prayer Night", isMajor: true },
  { id: "virtuous-woman", name: "Virtuous Woman Conference", date: "8th May 2026", time: "9:00 AM – 5:00 PM", location: "Christ's Heart Kampala – Mabirizi Complex", description: "A powerful three-day women's conference celebrating the strength, grace, and beauty of the godly woman. Featuring worship, keynote speakers, panel discussions, and ministry time focused on identity, purpose, and destiny. Women from all branches come together for a weekend of empowerment, sisterhood, and spiritual renewal.", tagline: "Crowned With Grace. Walking in Power.", category: "Women's Conference", isMajor: true },
  { id: "interbranch-overnight-kisaasi-may", name: "Interbranch Overnight Kisaasi", date: "15th May 2026", time: "8:00 PM – 6:00 AM", location: "Christ's Heart Kisaasi", description: "Multiple branches converge at the Kisaasi location for a powerful all-night prayer and worship gathering. An atmosphere of unity, intercession, and prophetic ministry as the body of Christ comes together across branch lines for a night of encounter.", tagline: "Branches Unite. Heaven Responds.", category: "Interbranch Overnight", isMajor: false },
  { id: "anniversary-chmi-nansana", name: "Anniversary CHMI Nansana", date: "17th May 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Nansana", description: "The Nansana branch celebrates its anniversary with a day of praise, thanksgiving, and powerful ministry. A growing community that has seen God's hand at work — this celebration honours every testimony and every victory experienced in this branch.", tagline: "Nansana Celebrates God's Hand at Work.", category: "Branch Anniversary", isMajor: false },
  { id: "mukono-overnight-may", name: "Mukono Overnight", date: "30th May 2026", time: "8:00 PM – 6:00 AM", location: "Christ's Heart Mukono", description: "An all-night prayer and worship experience at our Mukono branch. Believers gather for extended intercession, prophetic declarations, and a deep encounter with the Holy Spirit. Press into God's presence and receive fresh direction.", tagline: "A Night in His Presence Changes Everything.", category: "Prayer Night", isMajor: true },
  { id: "anniversary-chmi-bweyale", name: "Anniversary CHMI Bweyale", date: "1st June 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Bweyale", description: "Celebrating the Bweyale branch's anniversary with a special service of worship, testimonies, and a powerful word. The Bweyale community comes together to honour God for every breakthrough and every soul added to the kingdom through this branch.", tagline: "Bweyale Glorifies God.", category: "Branch Anniversary", isMajor: false },
  { id: "chmi-anniversary", name: "CHMI 19th Anniversary & Gerenge Prayer Camp", date: "5th June 2026", time: "All Day", location: "Gerenge, Uganda", description: "A landmark three-day celebration marking 19 years of Christ's Heart Ministries International. Combined with our powerful Gerenge Prayer Camp, this gathering unites believers from all branches in worship, thanksgiving, and intercession. Expect powerful testimonies, prophetic ministry, and a fresh outpouring as we celebrate God's faithfulness.", tagline: "19 Years of Apostolic Grace. The Best Is Yet to Come.", category: "Anniversary", isMajor: true },
  { id: "pastor-team-build", name: "Pastor Team Build", date: "9th June 2026", time: "9:00 AM – 5:00 PM", location: "Christ's Heart Kampala", description: "A dedicated leadership development day for all pastors and ministry leaders across the CHMI network. Featuring team-building exercises, strategic planning sessions, and leadership training. An investment in the shepherds who lead our branches and ministries worldwide.", tagline: "Stronger Leaders. Stronger Churches.", category: "Leadership", isMajor: true },
  { id: "interbranch-overnight-makerere-jun", name: "Interbranch Overnight Makerere", date: "12th June 2026", time: "8:00 PM – 6:00 AM", location: "Christ's Heart Makerere", description: "An all-night interbranch prayer gathering at the Makerere location. Students and community members from multiple branches converge for a night of intense worship, intercession, and prophetic ministry. The university community atmosphere adds a unique energy to this gathering.", tagline: "The Campus Burns With Prayer.", category: "Interbranch Overnight", isMajor: false },
  { id: "anniversary-chmi-iganga", name: "Anniversary CHMI Iganga", date: "28th June 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Iganga", description: "The Iganga branch celebrates its anniversary with praise, worship, and a powerful word. A day to reflect on God's goodness in the Iganga community and to declare His purposes for the season ahead.", tagline: "Iganga Declares God's Purposes.", category: "Branch Anniversary", isMajor: false },
  { id: "mukono-overnight-jun", name: "Mukono Overnight", date: "27th June 2026", time: "8:00 PM – 6:00 AM", location: "Christ's Heart Mukono", description: "An all-night prayer and worship experience at our Mukono branch. Believers gather for extended intercession, prophetic declarations, and a deep encounter with the Holy Spirit.", tagline: "A Night in His Presence Changes Everything.", category: "Prayer Night", isMajor: true },
  { id: "anniversary-chmi-mbarara", name: "Anniversary CHMI Mbarara", date: "4th July 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Mbarara", description: "Celebrating the Mbarara branch as it marks another year of kingdom expansion in western Uganda. A day of worship, testimonies of God's power, and a fresh prophetic word for the Mbarara community.", tagline: "Mbarara Celebrates Kingdom Expansion.", category: "Branch Anniversary", isMajor: false },
  { id: "anniversary-chmi-kampala", name: "Anniversary CHMI Kampala", date: "5th July 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Kampala", description: "The headquarters branch — Christ's Heart Kampala — celebrates its anniversary with a grand service of worship, powerful testimonies, and a prophetic word for the flagship community. As the mother church, this celebration carries a special weight and draws believers from across the network.", tagline: "The Mother Church Celebrates.", category: "Branch Anniversary", isMajor: false },
  { id: "interbranch-overnight-nansana-jul", name: "Interbranch Overnight Nansana", date: "10th July 2026", time: "8:00 PM – 6:00 AM", location: "Christ's Heart Nansana", description: "A powerful all-night gathering at the Nansana branch where multiple branches come together for a unified night of prayer, worship, and deep fellowship. Experience the power of corporate intercession as believers from different communities join in one accord.", tagline: "United in Prayer Through the Night.", category: "Interbranch Overnight", isMajor: false },
  { id: "anniversary-chmi-zambia", name: "Anniversary CHMI Zambia", date: "14th July 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Zambia", description: "Celebrating the Zambia branch of Christ's Heart Ministries International. A cross-border celebration of God's faithfulness as the Zambian community marks another year of growth, ministry, and kingdom impact in southern Africa.", tagline: "Beyond Borders. God's Grace in Zambia.", category: "Branch Anniversary", isMajor: false },
  { id: "the-blend", name: "The Blend", date: "18th July 2026", time: "9:00 AM – 6:00 PM", location: "Christ's Heart Kampala", description: "An inter-generational gathering where different generations of believers — from children to elders — come together in worship, fellowship, and ministry. The Blend celebrates unity across age groups, honouring what each generation carries and creating a powerful atmosphere where the old and new flow together in one Spirit.", tagline: "Generations United. One Spirit. One Vision.", category: "Conference", isMajor: true },
  { id: "mukono-overnight-jul", name: "Mukono Overnight", date: "25th July 2026", time: "8:00 PM – 6:00 AM", location: "Christ's Heart Mukono", description: "An all-night prayer and worship experience at our Mukono branch. Believers gather for extended intercession, prophetic declarations, and a deep encounter with the Holy Spirit.", tagline: "A Night in His Presence Changes Everything.", category: "Prayer Night", isMajor: true },
  { id: "babies-conference", name: "Babies Conference", date: "1st August 2026", time: "9:00 AM – 4:00 PM", location: "Christ's Heart Kampala", description: "A joyful and anointed conference dedicated to celebrating new life and equipping parents in raising the next generation. Featuring teaching on godly parenting, baby dedications, prayer over families, and practical sessions on raising children in faith. A must-attend for young families and expecting parents.", tagline: "A Generation Born for Greatness.", category: "Family", isMajor: true },
  { id: "anniversary-chmi-luweero", name: "Anniversary CHMI Luweero", date: "2nd August 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Luweero", description: "The Luweero branch celebrates its anniversary with a special service of praise and thanksgiving. A community known for resilience and faith gathers to honour God's sustaining grace and to prophesy into the next chapter of their journey.", tagline: "Luweero Stands Strong in Grace.", category: "Branch Anniversary", isMajor: false },
  { id: "interbranch-overnight-kisaasi-aug", name: "Interbranch Overnight Kisaasi", date: "14th August 2026", time: "8:00 PM – 6:00 AM", location: "Christ's Heart Kisaasi", description: "Multiple branches converge at the Kisaasi location for a powerful all-night prayer and worship gathering. An atmosphere of unity, intercession, and prophetic ministry as the body of Christ comes together for a night of encounter.", tagline: "Branches Unite. Heaven Responds.", category: "Interbranch Overnight", isMajor: false },
  { id: "anniversary-chmi-kyetume", name: "Anniversary CHMI Kyetume", date: "23rd August 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Kyetume", description: "Celebrating the Kyetume branch's anniversary with a powerful day of worship, testimonies, and prophetic declarations. The community gathers to celebrate God's faithfulness and to receive fresh vision for the season ahead.", tagline: "Kyetume Celebrates in Faith.", category: "Branch Anniversary", isMajor: false },
  { id: "anniversary-chmi-lira-biso", name: "Anniversary CHMI Lira & Biso", date: "29th August 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Lira & Biso", description: "A joint anniversary celebration for the Lira and Biso branches in northern Uganda. Two communities united in purpose gather to celebrate another year of God's grace, share testimonies, and receive a prophetic word for the next season.", tagline: "Northern Uganda Celebrates God's Grace.", category: "Branch Anniversary", isMajor: false },
  { id: "mukono-overnight-aug", name: "Mukono Overnight", date: "29th August 2026", time: "8:00 PM – 6:00 AM", location: "Christ's Heart Mukono", description: "An all-night prayer and worship experience at our Mukono branch. Believers gather for extended intercession, prophetic declarations, and a deep encounter with the Holy Spirit.", tagline: "A Night in His Presence Changes Everything.", category: "Prayer Night", isMajor: true },
  { id: "men-of-action", name: "Men of Action", date: "5th September 2026", time: "8:00 AM – 4:00 PM", location: "Christ's Heart Kampala", description: "A conference dedicated to building godly men who lead with integrity, purpose, and faith. Featuring dynamic speakers, breakout sessions on leadership, family, career, and spiritual warfare, plus powerful fellowship designed specifically for men ready to rise and take their God-given place.", tagline: "Rise. Lead. Transform.", category: "Men's Conference", isMajor: true },
  { id: "anniversary-chmi-kyebando", name: "Anniversary CHMI Kyebando", date: "6th September 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Kyebando", description: "The Kyebando branch celebrates its anniversary — one of the key branches in the Kampala network. A day of vibrant worship, powerful testimonies, and a prophetic word as this thriving community marks another year of God's faithfulness.", tagline: "Kyebando Thrives in God's Faithfulness.", category: "Branch Anniversary", isMajor: false },
  { id: "interbranch-overnight-kyebando-sep", name: "Interbranch Overnight Kyebando", date: "11th September 2026", time: "8:00 PM – 6:00 AM", location: "Christ's Heart Kyebando", description: "An electrifying all-night gathering at the Kyebando branch where multiple branches converge for a unified night of prayer, worship, and fellowship. The interbranch format creates a powerful atmosphere of corporate intercession.", tagline: "Many Branches. One Fire.", category: "Interbranch Overnight", isMajor: false },
  { id: "anniversary-chmi-canada", name: "Anniversary CHMI Canada", date: "18th September 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Canada", description: "Celebrating the Canada branch of Christ's Heart Ministries International. A cross-continental celebration of God's faithfulness as the Canadian community marks another year of growth, ministry, and kingdom impact in North America.", tagline: "From Africa to the Americas. God's Grace Knows No Border.", category: "Branch Anniversary", isMajor: false },
  { id: "anniversary-chmi-kalagi", name: "Anniversary CHMI Kalagi", date: "20th September 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Kalagi", description: "The Kalagi branch celebrates its anniversary with worship, testimonies, and a powerful word. A growing community that continues to see God move in remarkable ways gathers to celebrate and prophesy into the future.", tagline: "Kalagi Grows in God's Purpose.", category: "Branch Anniversary", isMajor: false },
  { id: "pastor-appreciation-kangulumira", name: "Pastor Appreciation Sunday & Kangulumira Anniversary", date: "27th September 2026", time: "9:00 AM – 3:00 PM", location: "Christ's Heart Kangulumira & All Branches", description: "A special Sunday across all branches dedicated to honouring and appreciating our pastors and spiritual leaders. Combined with the Kangulumira branch anniversary, this day celebrates the sacrificial service of those who shepherd the flock. Featuring tributes, gifts, prayer over pastors, and a powerful celebratory service.", tagline: "Honouring Those Who Shepherd Us.", category: "Leadership", isMajor: true },
  { id: "anniversary-chmi-banda", name: "Anniversary CHMI Banda", date: "29th September 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Banda", description: "Celebrating the Banda branch as it marks another year of gospel impact in the Banda community. A day filled with worship, heartfelt testimonies, and a celebratory message from leadership.", tagline: "Banda Celebrates God's Impact.", category: "Branch Anniversary", isMajor: false },
  { id: "mukono-overnight-sep", name: "Mukono Overnight", date: "26th September 2026", time: "8:00 PM – 6:00 AM", location: "Christ's Heart Mukono", description: "An all-night prayer and worship experience at our Mukono branch. Believers gather for extended intercession, prophetic declarations, and a deep encounter with the Holy Spirit.", tagline: "A Night in His Presence Changes Everything.", category: "Prayer Night", isMajor: true },
  { id: "anniversary-chmi-makerere", name: "Anniversary CHMI Makerere", date: "4th October 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Makerere", description: "The Makerere branch — located at Uganda's flagship university — celebrates its anniversary. A vibrant gathering of students and community members worshipping, testifying, and receiving a word of direction for the academic and spiritual season.", tagline: "The Campus Church Celebrates.", category: "Branch Anniversary", isMajor: false },
  { id: "interbranch-overnight-makerere-oct", name: "Interbranch Overnight Makerere", date: "9th October 2026", time: "8:00 PM – 6:00 AM", location: "Christ's Heart Makerere", description: "An all-night interbranch prayer gathering at the Makerere location. Students and community members from multiple branches converge for a night of intense worship, intercession, and prophetic ministry.", tagline: "The Campus Burns With Prayer.", category: "Interbranch Overnight", isMajor: false },
  { id: "anniversary-chmi-jinja", name: "Anniversary CHMI Jinja", date: "11th October 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Jinja", description: "Celebrating the Jinja branch at the source of the Nile. A special anniversary service with worship, testimonies, and a prophetic word. The Jinja community gathers to honour God for the mighty things He has done in this city.", tagline: "Jinja Flows With God's Power.", category: "Branch Anniversary", isMajor: false },
  { id: "anniversary-chmi-kisoro", name: "Anniversary CHMI Kisoro", date: "17th October 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Kisoro", description: "The Kisoro branch in the far south-west of Uganda celebrates its anniversary. Nestled near the borders of Congo and Rwanda, this community is a testament to the gospel reaching the furthest corners. A day of worship, celebration, and prophetic vision.", tagline: "To the Ends of the Earth. Kisoro Praises.", category: "Branch Anniversary", isMajor: false },
  { id: "anniversary-chmi-bugolobi", name: "Anniversary CHMI Bugolobi", date: "25th October 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Bugolobi", description: "Celebrating the Bugolobi branch in the heart of Kampala. A special anniversary service filled with worship, powerful testimonies, and a word from leadership. The Bugolobi community is known for its vibrant worship and strong fellowship.", tagline: "Bugolobi Worships With Passion.", category: "Branch Anniversary", isMajor: false },
  { id: "anniversary-chmi-ishaka", name: "Anniversary CHMI Ishaka", date: "28th October 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Ishaka", description: "The Ishaka branch celebrates its anniversary with a powerful service of worship and thanksgiving. A community in western Uganda that continues to grow and impact lives through the gospel of Jesus Christ.", tagline: "Ishaka Grows in Grace.", category: "Branch Anniversary", isMajor: false },
  { id: "mukono-overnight-oct", name: "Mukono Overnight", date: "31st October 2026", time: "8:00 PM – 6:00 AM", location: "Christ's Heart Mukono", description: "An all-night prayer and worship experience at our Mukono branch. Believers gather for extended intercession, prophetic declarations, and a deep encounter with the Holy Spirit.", tagline: "A Night in His Presence Changes Everything.", category: "Prayer Night", isMajor: true },
  { id: "anniversary-chmi-nairobi", name: "Anniversary CHMI Nairobi", date: "1st November 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Nairobi, Kenya", description: "Celebrating the Nairobi branch of Christ's Heart Ministries in Kenya. A cross-border celebration of God's faithfulness as the Kenyan community marks another year of growth, ministry, and kingdom impact in East Africa's capital city.", tagline: "Nairobi Stands Strong for the Gospel.", category: "Branch Anniversary", isMajor: false },
  { id: "anniversary-chmi-kisaasi", name: "Anniversary CHMI Kisaasi", date: "8th November 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Kisaasi", description: "The Kisaasi branch celebrates its anniversary with a vibrant service of worship, testimonies, and a prophetic word. One of the key branches in the greater Kampala area, Kisaasi continues to be a centre of spiritual transformation.", tagline: "Kisaasi Shines for Christ.", category: "Branch Anniversary", isMajor: false },
  { id: "november-blessing", name: "November Blessing", date: "9th November 2026", time: "9:00 AM – 5:00 PM Daily", location: "Christ's Heart Kampala – Mabirizi Complex", description: "Our annual week-long gathering of praise, worship, and prophetic declarations as we enter the season of thanksgiving. Join thousands of believers for seven days of supernatural encounters, divine blessings, and life-changing ministry.", tagline: "Step Into a Season of Supernatural Overflow.", category: "Conference", isMajor: true },
  { id: "mukono-overnight-nov", name: "Mukono Overnight", date: "28th November 2026", time: "8:00 PM – 6:00 AM", location: "Christ's Heart Mukono", description: "An all-night prayer and worship experience at our Mukono branch. Believers gather for extended intercession, prophetic declarations, and a deep encounter with the Holy Spirit.", tagline: "A Night in His Presence Changes Everything.", category: "Prayer Night", isMajor: true },
  { id: "anniversary-chmi-buloba-fortportal", name: "Anniversary CHMI Buloba & Fort Portal", date: "6th December 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Buloba & Fort Portal", description: "A joint anniversary celebration for the Buloba and Fort Portal branches. Two communities — one in greater Kampala and one in the western mountains — united in faith, celebrating God's faithfulness with worship, testimonies, and a powerful word.", tagline: "Two Branches, One Celebration of Grace.", category: "Branch Anniversary", isMajor: false },
  { id: "interbranch-overnight-kyebando-dec", name: "Interbranch Overnight Kyebando", date: "11th December 2026", time: "8:00 PM – 6:00 AM", location: "Christ's Heart Kyebando", description: "An electrifying all-night gathering at the Kyebando branch where multiple branches converge for a unified night of prayer, worship, and fellowship to close out the year. A powerful send-off into the festive season.", tagline: "Ending the Year in Prayer.", category: "Interbranch Overnight", isMajor: false },
  { id: "anniversary-chmi-gulu", name: "Anniversary CHMI Gulu", date: "13th December 2026", time: "10:00 AM – 3:00 PM", location: "Christ's Heart Gulu", description: "The Gulu branch in northern Uganda celebrates its anniversary. A community that has risen from the ashes of conflict to become a beacon of hope and faith. This anniversary is a powerful testament to God's redemptive power.", tagline: "Gulu Rises. Hope Prevails.", category: "Branch Anniversary", isMajor: false },
  { id: "children-bible-camp", name: "Children Bible Camp", date: "14th December 2026", time: "9:00 AM – 4:00 PM Daily", location: "Christ's Heart Kampala", description: "A fun-filled four-day Bible camp for children featuring interactive Bible teaching, games, crafts, drama, music, and fellowship. The Children Bible Camp is designed to build the faith foundation of the youngest members of our church family.", tagline: "Building Faith. Shaping Futures.", category: "Family", isMajor: true },
  { id: "honor-dinner", name: "Honor Dinner", date: "19th December 2026", time: "6:00 PM – 10:00 PM", location: "Christ's Heart Kampala", description: "An elegant two-evening gala dinner honouring the faithful servants, leaders, and partners of Christ's Heart Ministries International. A night of celebration, appreciation, awards, and fellowship as we close the year by recognising those who have gone above and beyond in service to God and the ministry.", tagline: "Honouring the Faithful. Celebrating the Journey.", category: "Celebration", isMajor: true },
  { id: "crossover-night", name: "Crossover Night", date: "31st December 2026", time: "10:00 PM – 2:00 AM", location: "All Branches", description: "Cross over into the new year in the presence of God. Our Crossover Night is a powerful all-branches gathering featuring extended worship, prophetic declarations, thanksgiving, and prayer as we usher in the new year with faith and expectation.", tagline: "Cross Over in Power. Enter the New Year With God.", category: "Special Service", isMajor: true },
];

async function main() {
  // Get existing Sanity event slugs
  const existing = await client.fetch(`*[_type == "event"]{ "slug": slug.current }`);
  const existingSlugs = new Set(existing.map((e) => e.slug));
  console.log(`Found ${existingSlugs.size} existing events in Sanity`);

  // Filter to missing events only
  const missing = LOCAL_EVENTS.filter((e) => !existingSlugs.has(e.id));
  console.log(`${missing.length} events to create\n`);

  if (missing.length === 0) {
    console.log("All events are already in Sanity!");
    return;
  }

  // Build mutations
  const mutations = missing.map((e) => {
    const dateStart = parseStartDate(e.date);
    const categoryRef = CATEGORY_MAP[e.category];

    if (!categoryRef) {
      console.warn(`  No category mapping for "${e.category}" (event: ${e.name})`);
    }

    const doc = {
      _id: `event-${e.id}`,
      _type: "event",
      name: e.name,
      slug: { _type: "slug", current: e.id },
      dateDisplay: e.date,
      ...(dateStart && { dateStart }),
      time: e.time,
      location: e.location,
      description: e.description,
      tagline: e.tagline,
      isMajor: e.isMajor,
      ...(categoryRef && {
        category: { _type: "reference", _ref: categoryRef },
      }),
    };

    return { createOrReplace: doc };
  });

  // Execute in batches of 20
  const BATCH_SIZE = 20;
  let created = 0;
  for (let i = 0; i < mutations.length; i += BATCH_SIZE) {
    const batch = mutations.slice(i, i + BATCH_SIZE);
    const tx = client.transaction();
    for (const mut of batch) {
      tx.createOrReplace(mut.createOrReplace);
    }
    await tx.commit();
    created += batch.length;
    console.log(`  Created batch ${Math.floor(i / BATCH_SIZE) + 1}: ${batch.length} events (${created}/${mutations.length})`);
  }

  console.log(`\nDone! ${created} events created in Sanity.`);
}

main().catch((err) => {
  console.error("Migration failed:", err);
  process.exit(1);
});
